spring:
  cloud:
    gateway:
      routes:
        - id: e-commerce-service
          uri: http://localhost:8080
          predicates:
            - Path=/item/**
            - Path=/users/**
            - Path=/products/**
            - Path=/categories/**
            - Path=/cart/**
            - Path=/vouchers/**
        - id: notification-service
          uri: http://localhost:8082
          predicates:
            - Path=/email/**
