spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: e-commerce
          uri: http://localhost:8080
          predicates:
            - Path=/users/**,/products/**,/categories/**,/item/**,/cart/**,/vouchers/**

        - id: email-microservice
          uri: http://localhost:8082
          predicates:
            - Path=/email/**
server:
  port: 8081